{{- if .Values.image.pullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dextinity-site-preview.fullname" . }}-image-pull-secret
  labels:
    {{- include "dextinity-site-preview.labels" . | nindent 8 }}
data:
  .dockerconfigjson: {{ required "Missing image.pullSecret" .Values.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
{{- end }}
